### ISSUE TITLE
Link to presentation materials concerning ATLAS/Helheim TLS work

### ISSUE THREAD

**Issue by adamlewinter** [CRREL/atlas.lidar.io#13]
We should post the posters, talks, papers, etc or links to external sites that have come from our work at Helheim.

**Comment by gadomski** [comment]
@adamlewinter I've added my AGU poster (and previous AGU citations) [here](http://atlas.lidar.io/dashboard#publications). Any others that you know of?

**Comment by adamlewinter** [comment]
@gadomski Here are a few more. Not sure if we want to post slideshows, too?
[LeWinter_AGU_2014_Poster_revised_large.pdf](https://github.com/CRREL/atlas.lidar.io/files/1616059/LeWinter_AGU_2014_Poster_revised_large.pdf)
[Finnegan_AGU_2015_Poster.pdf](https://github.com/CRREL/atlas.lidar.io/files/1616065/Finnegan_AGU_2015_Poster.pdf)

**Comment by gadomski** [comment]
Those posters are now up. I'd be good for slideshows if you want to throw any at me.
