### ISSUE TITLE
Add EFOY usage visual to track fuel consumption

### ISSUE THREAD

**Issue by adamlewinter** [CRREL/atlas.lidar.io#2]
@gadomski: It would be good to have some type of visual representation of EFOY usage. I imagine two versions, which could both be displayed: 

1) Usage Graph showing cumulative fuel usage for each EFOY. This would not break out by cartridge.

2) Individual EFOY fuel cartridge status bars. Similar to the battery bars, showing the depletion of each jug.

**Comment by gadomski** [comment]
@adamlewinter hackey versions of both are up: http://atlas.lidar.io/dashboard. Improvements tomorrow.

**Comment by gadomski** [comment]
Fixed by 248eaa46.
